### PR TITLE
Add IoT ESP8266-EVB Relay Example but with using npm esp8266-iotjs 

### PR DESCRIPTION
**Pull request by toome123**
Add the same example , but with using npm esp8266-iotjs

### CODE REVIEW

**Comment by Ignat99** [comment]
dependencies": {
-    "esp8266-iotjs": "0.0.1"
-  }

Here and made vulnerabilities to penetrate the system.

Вот так и вносятся уязвимости для проникновения в систему.
Я бы отменил все изменения которые вы внесли в этот репозитарий.

I am opposed to replace my examples. Your package I do not need. And personally I do not trust what you do with your package in the future.

Я против замены моих примеров. Ваш пакет мне соврешенно не нужен. И лично я совершенно не доверяю тому, что вы сделаете со своим пакетом в будущем.

**Comment by toome123** [comment]
Here is [Link](https://github.com/Smart-Dashboard/ESP8266-IoTJS.git) with public repo of npm package.. It is a simple way to handle board Events and control it.. I think it is useful for  Javascript Developers.. If you are  interested in programming in JavaScript , contributing is welcome.

**Comment by Ignat99** [comment]
https://samsung.github.io/iotjs/

May be better use more/less standard lib?
Or lib from Leon?

https://github.com/leon-anavi/esp8266-jadja

I not understand what are you doing.

If you use 

var express = require('express');

and 

var ws = require('websocket').server;

it is like install half Internet :-) You just made open security hole. IMHO

Neither of which monitoring can be no question in your case, it is not popular your public repo of npm package...

**Comment by Ignat99** [comment]
https://samsung.github.io/iotjs/

May be better use more/less standard lib?
Or lib from Lion?

I not understand what are you doing.

**Comment by toome123** [comment]
websockets is pretty much a good technology and I just wanted to try to make a module, which can operate with  firmware of olimex-IoT  , but of course, a better option is the mqtt  protocol. I strongly recommend to use ESP8266-JADJA by Leon Avani  and mqtt .. Contribute to Leon's repo. If you don't trust my npm module, don't use it. It is only for demo.

**Comment by Ignat99** [comment]
I did Survey-analysis of an important project on the node.js and python and I know what the surprises are in some packages (include websockets).

**Comment by leon-anavi** [comment]
Hi Dimitar, Ignat, thank you for the kind words and recommendations about MQTT and the open source project that I started esp8266-jadja. I appreciate it :)

In my opinion  Winnie-the-Pooh effect known as "the more, the more" applies with full force for the number of available open source examples for ESP8266 :)

**Comment by asofta** [comment]
Hi All, 
I already add MQTT support to latest olimex ESP8266/IoT Firmware/ project. 
If someone is interested i will fork olimex repo and add my modifications.
Current status of my port is: everything work without problems except small memory leakage on reconnect.
Exported functionallity to MQTT: Button, Relay, Adc, Mod-tc-mk2

**Comment by Ignat99** [comment]
Need fix small memory leakage first, IMHO. May by Vallgrind it is possibe?

http://valgrind.org/

It is a point of difference for corporation program and Open Source. Methodic of testing code.

**Comment by toome123** [comment]
@asofta  Hey, it will be great if you fork this repo end add your modifications. We can help you to improve it :)

**Pull request merged**
